Add Collect impl for hashbrown::HashMap/HashSet
kyren/gc-arena pull request #73
Opened 2023-06-06 01:35 UTC by Aaron1011

2023-06-08 00:28 UTC, moulins requested changes

2023-06-08 00:28 UTC, moulins commented on src/gc-arena/src/collect_impl.rs
> +    K: Eq + Hash + Collect,
The `K: Eq + Hash` bound is unnecessarily restrictive (the bound could also be removed from `std::HashMap`'s impl).

2023-06-08 00:28 UTC, moulins commented on src/gc-arena/src/collect_impl.rs
> +unsafe impl<T, S> Collect for hashbrown::HashSet<T, S>
Same remark as above.

2023-07-14 19:45 UTC, kyren commented
Handled by #77!

2023-07-14 19:45 UTC, closed without merging